### ISSUE TITLE
There was an error executing

### ISSUE THREAD

**Issue by SergiuSavva** [ricardoamaro/drupal-lxc-vagrant-docker#4]
There was an error executing ["sudo", "lxc-create", "--template", "vagrant-tmp-drupal-lxc-vagrant-docker_default_1408001380071_13983", "--name", "drupal-lxc-vagrant-docker_default_1408001380071_13983", "-f", "/home/gamer/.vagrant.d/boxes/quantal64/0/lxc/lxc.conf", "--", "--tarball", "/home/gamer/.vagrant.d/boxes/quantal64/0/lxc/rootfs.tar.gz", "--auth-key", "/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/keys/vagrant.pub"]

OS: Ubuntu 14.04
Vagrant: Installed Version: 1.6.3
lxc-ls: 1.0.5

**Comment by ricardoamaro** [comment]
can you try with https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box
